name: Build and Deploy Hub
on:
  - push
jobs:
  Generate-Antora-Site:
    name: Generate Antora site config
    runs-on: ubuntu-latest
    env:
      OUT_DIR: build
      PROJECT_SLUG: commodore-components-hub
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

      - name: Install Python Dependencies
        run: pip install --upgrade --upgrade-strategy eager -r requirements.txt

      - name: Generate Antora Site configuration
        run: python create-antora-site.py --path "$OUT_DIR" --slug "$PROJECT_SLUG"

      - name: Generate Antora Navigation
        run: python generate-nav.py > "$OUT_DIR"/"$PROJECT_SLUG"/docs/modules/ROOT/nav.adoc

      - name: Generate Antora Index
        run: python generate-index.py > "$OUT_DIR"/"$PROJECT_SLUG"/docs/modules/ROOT/pages/index.adoc

      - name: Generate Antora Playbook
        run: python generate-playbook.py > "$OUT_DIR"/"$PROJECT_SLUG"/playbook.yml

      - name: Upload generated site configuration
        uses: actions/upload-artifact@v2
        with:
          name: antora-site-configuration
          path: build/

  Build-Antora-Site:
    runs-on: ubuntu-latest
    needs: Generate-Antora-Site
    steps:
      - name: Download Antora site configuration
        uses: actions/download-artifact@v2
        with:
          name: antora-site-configuration

      - run: find .
      - run: cd components-hub; make html

  Deploy-Hub:
    runs-on: ubuntu-latest
    needs: Build-Antora-Site
    steps:
      - run: echo "Hallo"
