name: Build and Deploy Hub
on:
  - push
jobs:
  Generate-Antora-Site:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Generate Antora Site configuration
        run: echo "Generating the Antora Site configuration"

  Build-Antora-Site:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hallo"

  Deploy-Hub:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hallo"
