name: Python linting
on:
  pull_request:
    branches:
    - master

jobs:
  lints:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint_flake8
          - lint_pylint
          - lint_mypy
          - lint_black
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - uses: Gr1N/setup-poetry@v9
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: poetry install
      - name: Run ${{ matrix.command }}
        run: make ${{ matrix.command }}
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - uses: Gr1N/setup-poetry@v9
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: poetry install
      - run: make test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
